apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: cloudexperts/spring-petclinic:a50ef03d16ab8f519c37ad600d560e86e1aa3c6d
          ports:
            - containerPort: 8080